/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TradeSymbol } from "./models";
import { WebsocketConnection } from "@rhiaqey/sdk-ts";
export { TradeSymbol } from "./models";
export { WebsocketConnection } from "@rhiaqey/sdk-ts";
export namespace Components {
    interface RqMtMarquee {
        "animation": boolean;
        "apiHost": string;
        "apiKey": string;
        "channels": string | string[];
        "endpoint": string;
        "symbols": TradeSymbol[];
    }
    interface RqMtRates {
    }
    interface RqSingleQuote {
        "apiHost": string;
        "apiKey": string;
        "channels": string | string[];
        "endpoint": string;
        "setConnection": (conn: WebsocketConnection) => Promise<void>;
        "symbol"?: string;
    }
}
declare global {
    interface HTMLRqMtMarqueeElement extends Components.RqMtMarquee, HTMLStencilElement {
    }
    var HTMLRqMtMarqueeElement: {
        prototype: HTMLRqMtMarqueeElement;
        new (): HTMLRqMtMarqueeElement;
    };
    interface HTMLRqMtRatesElement extends Components.RqMtRates, HTMLStencilElement {
    }
    var HTMLRqMtRatesElement: {
        prototype: HTMLRqMtRatesElement;
        new (): HTMLRqMtRatesElement;
    };
    interface HTMLRqSingleQuoteElement extends Components.RqSingleQuote, HTMLStencilElement {
    }
    var HTMLRqSingleQuoteElement: {
        prototype: HTMLRqSingleQuoteElement;
        new (): HTMLRqSingleQuoteElement;
    };
    interface HTMLElementTagNameMap {
        "rq-mt-marquee": HTMLRqMtMarqueeElement;
        "rq-mt-rates": HTMLRqMtRatesElement;
        "rq-single-quote": HTMLRqSingleQuoteElement;
    }
}
declare namespace LocalJSX {
    interface RqMtMarquee {
        "animation"?: boolean;
        "apiHost"?: string;
        "apiKey"?: string;
        "channels"?: string | string[];
        "endpoint"?: string;
        "symbols"?: TradeSymbol[];
    }
    interface RqMtRates {
    }
    interface RqSingleQuote {
        "apiHost"?: string;
        "apiKey"?: string;
        "channels"?: string | string[];
        "endpoint"?: string;
        "symbol"?: string;
    }
    interface IntrinsicElements {
        "rq-mt-marquee": RqMtMarquee;
        "rq-mt-rates": RqMtRates;
        "rq-single-quote": RqSingleQuote;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rq-mt-marquee": LocalJSX.RqMtMarquee & JSXBase.HTMLAttributes<HTMLRqMtMarqueeElement>;
            "rq-mt-rates": LocalJSX.RqMtRates & JSXBase.HTMLAttributes<HTMLRqMtRatesElement>;
            "rq-single-quote": LocalJSX.RqSingleQuote & JSXBase.HTMLAttributes<HTMLRqSingleQuoteElement>;
        }
    }
}
