/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TradeSymbolCategory } from "./models";
export { TradeSymbolCategory } from "./models";
export namespace Components {
    interface RqMtMarquee {
        "animation": boolean;
        "apiHost": string;
        "apiKey": string;
        "channels": string | string[];
        "endpoint": string;
        "namespace": string;
        "symbols": TradeSymbol[];
    }
    interface RqMtRates {
        "animation": boolean;
        "apiHost": string;
        "apiKey": string;
        "channels": string | string[];
        "endpoint": string;
        "groups": TradeSymbolCategory[];
        "namespace": string;
        "selected_tab": string;
        "size": 'default' | 'large';
    }
}
declare global {
    interface HTMLRqMtMarqueeElement extends Components.RqMtMarquee, HTMLStencilElement {
    }
    var HTMLRqMtMarqueeElement: {
        prototype: HTMLRqMtMarqueeElement;
        new (): HTMLRqMtMarqueeElement;
    };
    interface HTMLRqMtRatesElement extends Components.RqMtRates, HTMLStencilElement {
    }
    var HTMLRqMtRatesElement: {
        prototype: HTMLRqMtRatesElement;
        new (): HTMLRqMtRatesElement;
    };
    interface HTMLElementTagNameMap {
        "rq-mt-marquee": HTMLRqMtMarqueeElement;
        "rq-mt-rates": HTMLRqMtRatesElement;
    }
}
declare namespace LocalJSX {
    interface RqMtMarquee {
        "animation"?: boolean;
        "apiHost"?: string;
        "apiKey"?: string;
        "channels"?: string | string[];
        "endpoint"?: string;
        "namespace"?: string;
        "symbols"?: TradeSymbol[];
    }
    interface RqMtRates {
        "animation"?: boolean;
        "apiHost"?: string;
        "apiKey"?: string;
        "channels"?: string | string[];
        "endpoint"?: string;
        "groups"?: TradeSymbolCategory[];
        "namespace"?: string;
        "selected_tab"?: string;
        "size"?: 'default' | 'large';
    }
    interface IntrinsicElements {
        "rq-mt-marquee": RqMtMarquee;
        "rq-mt-rates": RqMtRates;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rq-mt-marquee": LocalJSX.RqMtMarquee & JSXBase.HTMLAttributes<HTMLRqMtMarqueeElement>;
            "rq-mt-rates": LocalJSX.RqMtRates & JSXBase.HTMLAttributes<HTMLRqMtRatesElement>;
        }
    }
}
