name: Commit

on:
  push:
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 20.x ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: NPM install
        run: |
          npm install
          npm run build
          npm run copy

      - name: NPM test
        run: |
          npm run test
